spring:
    application:
            name: ratail-sku
    datasource:
        url: jdbc:mysql://localhost:3306/retail
        username: root
        password: 123456
server:
  port: 10001
---
spring:
  profiles: sit
  datasource:
      url: jdbc:mysql://54.255.182.198:3306/retail
      username: retail
      password: retail__123