spring:
    application:
            name: ratail-sku
    jpa:
        hibernate:
          ddl-auto: update
    datasource:
        url: jdbc:mysql://localhost:3306/retail
        username: root
        password: 123456
server:
  port: 10001
---
spring:
  profiles: sit
  datasource:
      url: jdbc:mysql://localhost:3306/retail
      username: futureretail
      password: futureretail